server:
  mode: debug
  port: :8080
  jwtkey: hellogo

mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  name: ggblog

redis:
  addr: localhost:6379
  db: 0
  poolsize: 100

qiniu:
  accesskey: 0Kpw-ItaVA9JTa1ZMiloRUqYRt5Bcof_dOGbbdP9
  secretkey: YaNc-e7DlmtYzQL_SuMDLT5XWGn-VLO_dW_Psbku
  bucket: ggbloglian
  server: http://sefzgm5p6.hd-bkt.clouddn.com/

services:
  gateway:
    addr: 127.0.0.1:10001
  user:
    addr: 127.0.0.1:10002
  article:
    addr: 127.0.0.1:10003